### ISSUE TITLE
entity ui issue

### ISSUE THREAD

**Issue by lovelybhushan13** [hypersign-protocol/studio#121]
- [x] enter by default value in all the field

like in schema name-Enter schema name, in the name field - Enter attribute Name( give an example of camelcase)
![image](https://user-images.githubusercontent.com/90840933/199408328-c148532a-070a-4106-b85f-6f650f2ebdba.png)

- [x] while clicking on create a button in the credential page, getting the issuer did already 
field
steps to recreate this

1. create on credential and save it
2. then click on create button
![image](https://user-images.githubusercontent.com/90840933/199410275-24e15cb1-7a3d-42e4-a851-001d6cea0d4f.png)

- [x] on entering the status reason first then the status, its getting blank.
![image](https://user-images.githubusercontent.com/90840933/199411370-73a905e2-e8b3-4c1b-8527-b1b6f1daff7b.png)

- [x] in the presentation page also display the default value in all the fields 
![image](https://user-images.githubusercontent.com/90840933/199411618-0dfe3f1e-8a79-4a46-b2bd-c7dbd03f5969.png)

- [x] add this type to the icon for schema, credential, and presentation page
![image](https://user-images.githubusercontent.com/90840933/199412916-40e740a3-4bff-4e2c-a648-31aa38f62b1b.png)

- [x] display validation for entering Url in the name field  while creating presentation
![image](https://user-images.githubusercontent.com/90840933/199459126-f6f399bd-fb96-43eb-9bbc-4ec656aa3d93.png)

- [x] click on the create button on any page slide bar will open, close the slide bar. here button is displaying blue in color, it should become yellow. the same issue for the save button 
![image](https://user-images.githubusercontent.com/90840933/199714920-d828f95d-04f4-45d8-86fa-1232286e6597.png)
![image](https://user-images.githubusercontent.com/90840933/199714967-d4ae3cf3-2e49-4d5e-ac9e-5427e34fb867.png)

**Comment by Pratap2018** [comment]
https://github.com/hypersign-protocol/studio-frontend/pull/37
