### ISSUE TITLE
Schema text field bug

### ISSUE THREAD

**Issue by lovelybhushan13** [hypersign-protocol/studio#37]
- [x] Schema text field is not working properly, on entering any schema name in the text field it's showing the word Schema By default in the text field.
 
![image](https://user-images.githubusercontent.com/90840933/194299058-9d088000-6e0b-4002-80e9-b539185ab4b4.png)

 - [x] validation should be displayed on entering the URL in the schema name as an invalid schema name 
 - [x] make schema name textbox mandatory
 - [x] add validation msg on keeping the description text box blank
 - [x] add validation msg on entering URL in the name text box
 - [ ] add validation msg on entering text with space in the name text box
 - [x] type textbox should be like dropbox with all the data types which user can select
 - [x] add validation for keeping the format textbox blank
 - [x] add validation entering invalid text like URL in the format textbox 
 - [x] getting filled field value 
    
![image](https://user-images.githubusercontent.com/90840933/195087190-ae7d04d2-467d-4be7-9c9d-89e2cfd611dd.png)

**Comment by varsha766** [comment]
@lovelybhushan13  
Description and  format is not mandatory so it can be left empty.
